---
version: 2

build:
    os: ubuntu-22.04
    tools:
        python: '3.12'
    jobs:
        pre_build:
        -   make build

submodules:
    include: all
    recursive: true

mkdocs:
    configuration: mkdocs.yml

python:
    install:
    -   requirements: requirements.txt
