---
site_name: The brain imaging data structure
repo_url: https://github.com/bids-standard/in_darkness_bind_them
site_url: https://in-darkness-bind-them.readthedocs.io/en/latest

plugins:
-   search
-   tags
-   social
-   blog
    # post_url_format: "{date}/{slug}"
-   rss:
        match_path: blog/posts/.*
        date_from_meta:
            as_creation: date
        categories:
        -   categories
        -   tags

docs_dir: docs

exclude_docs: |
    .github
    starter_kit/.faq/
    starter_kit/questions/
    starter_kit/reports/
    website/_bep_collection/
    website/_pages/news
    website/_posts/
    website/_pages/news.md
    website/_redirects/
    website/templates/
    apps/README.md
    execution/README.md
    execution/BIDS_logo/README.md
    extensions/README.md
    starter_kit/README.md
    starter_kit/matlabCode/general/README.md
    starter_kit/src/CODE_OF_CONDUCT.md
    starter_kit/src/tutorials/media/README.md
    starter_kit/src/CONTRIBUTING.md
    stats_models/README.md
    stats_models/bsmschema/README.md
    stats_models/specification/walkthrough-2.md
    website/README.md
    website/tools/README.md

nav:
-   index.md
-   Standards:
    -   website/_pages/specification.md
    -   BIDS schema:
        -   extensions/docs/schema.md
        -   how it works:
            -   extensions/docs/how-the-schema-works.md
            -   metadata: extensions/docs/schema_meta.md
            -   objects: extensions/docs/schema_objects.md
            -   rules: extensions/docs/schema_rules.md
        -   details:
            -   specification/schema/README.md
    -   BIDS stats model:
        -   stats_models/specification/index.md
        -   motivations: stats_models/specification/motivation.md
        -   walkthrough:
            -   stats_models/specification/walkthrough-intro.md
            -   part-1: stats_models/specification/walkthrough-1.md
        -   integration: stats_models/specification/integration.md
        -   legacy: stats_models/specification/legacy.md
        -   specification:
            -   stats_models/specification/spec.md
            -   reference: stats_models/specification/reference.md
        -   examples and resources:
            -   stats_models/specification/model-zoo.md
            -   default model: stats_models/specification/default_model.md
        -   variable transforms:
            -   variable-transform/README.md
            -   compute: variable-transform/spec/compute.md
            -   munge: variable-transform/spec/munge.md
    -   BIDS app specification:
        -   execution/src/index.md
        -   scope: execution/src/scope.md
        -   specification:
            -   execution/src/specification.md
            -   user interface: execution/src/ui.md
            -   inputs: execution/src/inputs.md
            -   outputs: execution/src/outputs.md
            -   examples: execution/src/examples.md
            -   release notes: execution/src/CHANGELOG.md
-   Getting started:
    -   starter_kit/src/index.md
    -   folders and files:
        -   folders: starter_kit/src/folders_and_files/folders.md
        -   files: starter_kit/src/folders_and_files/files.md
        -   metadata: starter_kit/src/folders_and_files/metadata.md
        -   json_101: stats_models/specification/json_101.md
        -   derivatives: starter_kit/src/folders_and_files/derivatives.md
    -   tutorials:
        -   starter_kit/src/tutorials/tutorials.md
        -   conversion:
            -   asl: starter_kit/src/tutorials/asl.md
            -   ieeg: starter_kit/src/tutorials/ieeg.md
            -   mri: starter_kit/src/tutorials/mri.md
            -   pet: starter_kit/src/tutorials/pet.md
        -   annotation: starter_kit/src/tutorials/annotation.md
    -   resources:
        -   starter_kit/src/links.md
        -   talks: starter_kit/src/talks.md
        -   publications: starter_kit/src/publications.md
        -   dependencies: starter_kit/src/dependencies.md
        -   glossary: starter_kit/src/glossary.md
-   Datasets:
    -   starter_kit/src/dataset_examples.md
    -   examples: examples/README.md
-   Tools:
    -   website/_pages/benefits.md
    -   Validator: starter_kit/src/validator.md
    -   BIDS apps:
        -   apps/about.md
        -   tutorial: apps/tutorial.md
        -   dashboard: apps/apps.md
-   Extensions:
    -   website/_pages/get_involved.md
    -   intro: extensions/docs/index.md
    -   general_guidelines: extensions/docs/general_guidelines.md
    -   guide: extensions/docs/guide.md
    -   submission: extensions/docs/submission.md
    -   macros: specification/macros_doc.md
-   Community:
    -   Governance: website/_pages/governance.md
    -   Code of conduct:
        -   specification: specification/CODE_OF_CONDUCT.md
        -   starter_kit: starter_kit/CODE_OF_CONDUCT.md
        -   website: website/_pages/code_of_conduct.md
    -   contributing:
        -   apps: apps/CONTRIBUTING.md
        -   grant: grant/CONTRIBUTING.md
        -   wesbite: website/CONTRIBUTING.md
        -   spec: specification/CONTRIBUTING.md
        -   bids apps spec: execution/src/CONTRIBUTING.md
        -   starter_kit: starter_kit/CONTRIBUTING.md
-   FAQ:
    -   general: starter_kit/src/FAQ.md
    -   extensions: extensions/docs/faq.md
    -   bids apps: apps/dev_faq.md
-   Blog:
    -   blog/index.md
-   Impact:
    -   grant/README.md
-   Contact: starter_kit/src/contact.md

theme:
    name: material
    favicon: assets/favicon/favicon.ico
    logo: starter_kit/src/images/logo.png
    features:
    -   content.action.edit
    -   header.autohide
    -   navigation.footer
    -   navigation.indexes
    -   navigation.instant
    -   navigation.path
    -   navigation.sections
    -   navigation.tabs
    -   navigation.tabs.sticky
    -   navigation.top
    -   search.suggest
    -   search.highlight
    -   toc.follow
    icon:
        repo: fontawesome/brands/github
        edit: material/pencil
    palette:
    -   media: (prefers-color-scheme)
        toggle:
            icon: material/brightness-auto
            name: Switch to light mode
    -   media: '(prefers-color-scheme: light)'
        scheme: default
        toggle:
            icon: material/brightness-7
            name: Switch to dark mode
    -   media: '(prefers-color-scheme: dark)'
        scheme: slate
        toggle:
            icon: material/brightness-4
            name: Switch to system preference

edit_uri: https://github.com/bids-standard/bids-extensions/edit/main/docs/

markdown_extensions:
-   tables
-   toc:
        anchorlink: true
-   pymdownx.details
-   admonition
-   pymdownx.superfences:
        custom_fences:
        -   name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
-   https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
-   javascripts/tablesort.js


copyright: Copyright &copy; BIDS Contributors - <a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a>

extra:
    generator: false
    social:
    -   icon: fontawesome/brands/x-twitter
        link: https://x.com/BIDSstandard/
    -   icon: fontawesome/brands/mastodon
        link: https://fosstodon.org/@bidsstandard
    -   icon: fontawesome/brands/google
        link: https://groups.google.com/g/bids-discussion
    -   icon: fontawesome/brands/instagram
        link: https://www.instagram.com/bidsstandard/
    -   icon: fontawesome/brands/youtube
        link: https://www.youtube.com/channel/UCxZUcYfd_nvIVWAbzRB1tlw
