[tool.black]
line-length = 79

[tool.codespell]
ignore-words-list = "nd,manuel,ALS,TE,Acknowledgements,"
skip = ".git,env,specification,starter_kit,examples,grant,apps,execution,pyproject.toml"

[tool.isort]
combine_as_imports = true
line_length = 79
profile = "black"
skip_gitignore = true
