[tool.black]
line-length = 79

[tool.codespell]
ignore-words-list = "Acknowledgements,als,ans,asai,nd,manuel,te"
skip = ".git,env,specification,starter_kit,examples,apps,execution,pyproject.toml,data/affiliations.tsv,docs/collaboration/contributors.md,data/papers.json"

[tool.isort]
combine_as_imports = true
line_length = 79
profile = "black"
skip_gitignore = true
